services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: event-notification-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: app_user
      RABBITMQ_DEFAULT_PASS: app_password
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - event-notification-network
  producer:
    build:
      context: .
      dockerfile: apps/producer/Dockerfile
    env_file:
      - .env.docker
    container_name: event-notification-producer
    ports:
      - '3000:3000'
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - event-notification-network
  consumer:
    build:
      context: .
      dockerfile: apps/consumer/Dockerfile
    env_file:
      - .env.docker
    container_name: event-notification-consumer
    ports:
      - '3001:3001'
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - event-notification-network
  telegram-notifier:
    build:
      context: .
      dockerfile: apps/telegram-notifier/Dockerfile
    env_file:
      - .env.docker
    container_name: event-notification-telegram-notifier
    ports:
      - '3002:3002'
    networks:
      - event-notification-network

networks:
  event-notification-network:
    driver: bridge
